---
openapi: 3.0.1
info:
  title: API v1
  version: v1
paths:
  "/api/v1/categories":
    get:
      summary: list categories
      tags:
      - Categories
      responses:
        '200':
          description: List of categories
  "/api/v1/categories/{id}":
    get:
      summary: Retrieves a category
      tags:
      - Categories
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: category found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                required:
                - id
                - title
        '404':
          description: category not found
        '406':
          description: unsupported accept header
  "/orders":
    post:
      summary: Creates a order
      tags:
      - Order
      parameters: []
      responses:
        '201':
          description: blog created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                user_address:
                  type: string
                user_number:
                  type: integer
                line_items_attributes:
                  type: array
                  items:
                    properties:
                      quantity:
                        type: string
                      product_id:
                        type: integer
              required:
              - user_name
              - user_address
              - user_number
  "/api/v1/products":
    get:
      summary: list products
      tags:
      - Products
      responses:
        '200':
          description: List of products
  "/api/v1/products/{id}":
    get:
      summary: Retrieves a products
      tags:
      - Products
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: category found
        '404':
          description: product not found
        '406':
          description: unsupported accept header
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
